//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VersionMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public string Id_Alumno { get; set; }
        public string Nom_Alumno { get; set; }
        public string Dir_Alumno { get; set; }
        public Nullable<long> Tel_Alumno { get; set; }
        public string Grp_Alumno { get; set; }
    }
}
