//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VersionMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docente
    {
        public string ID_Docente { get; set; }
        public string Nom_Docente { get; set; }
        public string Dire_Docente { get; set; }
        public Nullable<long> Tel_Docente { get; set; }
    }
}
